#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 16, 2018 04:15:48 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import registration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    registration_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    registration_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+462+142")
        top.title("New Toplevel")
        top.configure(background="#656297")



        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.35, rely=0.16,height=20, relwidth=0.27)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.labelRegistration = Label(top)
        self.labelRegistration.place(relx=0.05, rely=0.02, height=21, width=69)
        self.labelRegistration.configure(background="#d9d9d9")
        self.labelRegistration.configure(disabledforeground="#a3a3a3")
        self.labelRegistration.configure(foreground="#000000")
        self.labelRegistration.configure(text='''Registration''')

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.35, rely=0.24,height=20, relwidth=0.27)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Entry3 = Entry(top)
        self.Entry3.place(relx=0.35, rely=0.33,height=20, relwidth=0.27)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")

        self.Entry4 = Entry(top)
        self.Entry4.place(relx=0.35, rely=0.56,height=20, relwidth=0.27)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Listbox1 = Listbox(top)
        self.Listbox1.place(relx=0.35, rely=0.4, relheight=0.12, relwidth=0.27)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(width=164)

        self.Entry5 = Entry(top)
        self.Entry5.place(relx=0.35, rely=0.64,height=20, relwidth=0.27)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")

        self.buttonSubmit = Button(top)
        self.buttonSubmit.place(relx=0.37, rely=0.76, height=24, width=49)
        self.buttonSubmit.configure(activebackground="#d9d9d9")
        self.buttonSubmit.configure(activeforeground="#000000")
        self.buttonSubmit.configure(background="#d9d9d9")
        self.buttonSubmit.configure(disabledforeground="#a3a3a3")
        self.buttonSubmit.configure(foreground="#000000")
        self.buttonSubmit.configure(highlightbackground="#d9d9d9")
        self.buttonSubmit.configure(highlightcolor="black")
        self.buttonSubmit.configure(pady="0")
        self.buttonSubmit.configure(text='''Submit''')

        self.buttonCancel = Button(top)
        self.buttonCancel.place(relx=0.52, rely=0.76, height=24, width=47)
        self.buttonCancel.configure(activebackground="#d9d9d9")
        self.buttonCancel.configure(activeforeground="#000000")
        self.buttonCancel.configure(background="#d9d9d9")
        self.buttonCancel.configure(disabledforeground="#a3a3a3")
        self.buttonCancel.configure(foreground="#000000")
        self.buttonCancel.configure(highlightbackground="#d9d9d9")
        self.buttonCancel.configure(highlightcolor="black")
        self.buttonCancel.configure(pady="0")
        self.buttonCancel.configure(text='''Cancel''')

        self.labelName = Label(top)
        self.labelName.place(relx=0.27, rely=0.16, height=21, width=38)
        self.labelName.configure(background="#d9d9d9")
        self.labelName.configure(disabledforeground="#a3a3a3")
        self.labelName.configure(foreground="#000000")
        self.labelName.configure(text='''Name''')

        self.labelUserId = Label(top)
        self.labelUserId.place(relx=0.27, rely=0.24, height=21, width=40)
        self.labelUserId.configure(background="#d9d9d9")
        self.labelUserId.configure(disabledforeground="#a3a3a3")
        self.labelUserId.configure(foreground="#000000")
        self.labelUserId.configure(text='''UserID''')

        self.labelFaculty = Label(top)
        self.labelFaculty.place(relx=0.27, rely=0.33, height=21, width=44)
        self.labelFaculty.configure(background="#d9d9d9")
        self.labelFaculty.configure(disabledforeground="#a3a3a3")
        self.labelFaculty.configure(foreground="#000000")
        self.labelFaculty.configure(text='''Faculty''')

        self.labelCourses = Label(top)
        self.labelCourses.place(relx=0.27, rely=0.42, height=21, width=48)
        self.labelCourses.configure(background="#d9d9d9")
        self.labelCourses.configure(disabledforeground="#a3a3a3")
        self.labelCourses.configure(foreground="#000000")
        self.labelCourses.configure(text='''Courses''')

        self.labelPassword = Label(top)
        self.labelPassword.place(relx=0.23, rely=0.56, height=21, width=56)
        self.labelPassword.configure(background="#d9d9d9")
        self.labelPassword.configure(disabledforeground="#a3a3a3")
        self.labelPassword.configure(foreground="#000000")
        self.labelPassword.configure(text='''Password''')

        self.labelConPassword = Label(top)
        self.labelConPassword.place(relx=0.17, rely=0.64, height=21, width=103)
        self.labelConPassword.configure(background="#d9d9d9")
        self.labelConPassword.configure(disabledforeground="#a3a3a3")
        self.labelConPassword.configure(foreground="#000000")
        self.labelConPassword.configure(text='''Confirm Password''')






if __name__ == '__main__':
    vp_start_gui()



